services:
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn fam_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: fam_backend:v2
    env_file:
      - .env
    # depends_on:
    #   - redis
    restart: unless-stopped

  # Since we are using remote redis instance url 
  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped

  celery:
    build: .
    command: celery -A fam_backend worker -l info -Q default,youtube_deadletter
    depends_on:
      # - redis
      - web
    env_file:
      - .env
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A fam_backend beat -l info
    depends_on:
      # - redis
      - web
    env_file:
      - .env
    restart: unless-stopped